### ISSUE TITLE
Naštudovať si SDK a Kameru

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#12]

**Comment by TriumphST** [comment]
Ako sa robí ROI 
V akom formáte kamera ukladá záznam
Nájsť všetky ďalšie funkcie, ktoré budeme potrebovať podľa katalógu požiadaviek
Aké parametre vieme nastaviť kamere (expozícia, jas, saturácia....)
Ako spojiť SDK s Visual aplikáciou Kubo
Prípadne Wimba
Doskúšať všetky technológie (SDK) aby sme vedeli spraviť návrh.
Napr. na ROI by tam malo byť.

**Comment by pavelpetrovic** [comment]
interesting link: https://docs.microsoft.com/en-us/windows/desktop/medfound/mfcaptured3d-sample
