### ISSUE TITLE
GUI V moqupe

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#13]

**Comment by Emilmilill** [comment]
[Mockup.pdf](https://github.com/TIS2018-FMFI/vysokorychlostna-kamera/files/2522709/Mockup.pdf)

Tu je prvotný mockup návrh systému.

**Comment by pavelpetrovic** [comment]
ten zvoleny priecinok tam nebude niekde zobrazeny?
issue zavrite, az ked to prediskutujete so zadavatelom. 
navrh gui treba, prosim, osobne prediskutovat s niektorym zo zadavatelov.

**Comment by Emilmilill** [comment]
Jasné, rozumiem.
Vybratý priečinok bude zobrazený tam, kde je teraz "vyberte priečinok". Po vybratí priečinka sa zobazí, aký priečinok je vybratý.

**Comment by Emilmilill** [comment]
https://drive.google.com/file/d/1tAkSylh5KYRv7KU0EK66xKOlOdCQOwE4/view?usp=sharing
