### ISSUE TITLE
Varga - info

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#15]
Zistit od zadavatela cb alebo farebna - ake vsetky kamery mame podporovat
Poslať mu prepis prvého stretnutia (len formálne)
Zistiť, ako je to s fps

**Comment by muller29** [comment]
Všetky kamery Allied Vision s ktorými náš systém bude vedieť pracovať sú čierno-biele.
Formálny súhlas už máme, opravili sme čo bolo treba.
Keď sa sníži fps, tak to bude pomalšie prehrávať.
