### ISSUE TITLE
návh systému

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#18]
A. podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované
B. podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov.
C. návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom
D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by Emilmilill** [comment]
Toto issue som nahradil milestoneom a vytvoril viacero issues, ktore som mu priradil

**Comment by pavelpetrovic** [comment]
zo stretnutia:

JE ZVLADNUTE ZOBRAzovanie vimba kamery v MFC okne
--
navrhnute GUI treba osobne prediskutovat so zadavelom
testovacie scenare su pripravene, este prosim doplnit cisla akcii aj scenarov a potom ked bude aplikacia rozdelena na komponenty kazdy za svoje komponenty doplni ako ich bude testovat
CImage vyzera dobre - ma aj Save, GetBits - takto mozno v pamati efektivne ukladat iba samotne data s hodnotami pixlov a pomocou CopyMemory rychlo kopirovat
 
na timovych stretnutiach sa maju zucastnovat vsetci a ulohy treba pridelit vsetkym clenom
do zapisnic zapisovat poriadne, co sa prediskutovalo a ako to dopadlo, co sa zistilo...
 
mame sklz, treba sa pokusit dohnat:
- co najskor dotestovat technolgie (vykusovanie mensieho vyseku)
- rychle ukladanie do pamate
- v pozadi z druheho vlakna ukaldanie do png
- dokoncit navrh  a poslat mailom co najskor
