### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by Emilmilill** [TIS2018-FMFI/vysokorychlostna-kamera#24]

**Comment by TriumphST** [comment]
![komponent_diagram](https://user-images.githubusercontent.com/33921752/49796091-06dfde80-fd3c-11e8-9fd9-83af43c9fd89.png)

**Comment by TriumphST** [comment]
![komponent_diagram_v2](https://user-images.githubusercontent.com/33921752/49796889-32fc5f00-fd3e-11e8-85b6-18af44b92adb.png)

**Comment by TriumphST** [comment]
![komponent_diagram_v3](https://user-images.githubusercontent.com/33921752/49797462-d437e500-fd3f-11e8-99c2-145f0b17094d.png)
