### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by muller29** [TIS2018-FMFI/vysokorychlostna-kamera#32]
Napísať testovacie scenáre a nahodiť ich sem.

**Comment by muller29** [comment]
[Testovacie scenáre.docx](https://github.com/TIS2018-FMFI/vysokorychlostna-kamera/files/2617579/Testovacie.scenare.docx)

**Comment by pavelpetrovic** [comment]
skuste si prejst vsetky poziadavky katalogu poziadaviek a skontrolovat, ktore poziadavky su testovacimi scenarmi pokryte a ktore nie.  idealne by mali byt pokryte vsetky.

**Comment by muller29** [comment]
Dobre, prejdem to a pridám tam ešte na chýbajúce časti.
Traja by sme vedeli s Vami stretnúť vo štvrtok od 9:50 do 11:30. Máte vtedy
čas na rýchle strenutie s nami?

Pavel Petrovič <notifications@github.com> ezt írta (időpont: 2018. nov.
27., K, 0:35):

**Comment by muller29** [comment]
[Testovacie scenáre.docx](https://github.com/TIS2018-FMFI/vysokorychlostna-kamera/files/2642916/Testovacie.scenare.docx)

**Comment by muller29** [comment]
Ocislovane:
[Testovacie scenáre.docx](https://github.com/TIS2018-FMFI/vysokorychlostna-kamera/files/2666598/Testovacie.scenare.docx)
