### ISSUE TITLE
Camera ukladanie

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#34]
CImage -> CImage::GetBits -> memcpy/memorycopy?

**Comment by TriumphST** [comment]
CImage::GetBPP

**Comment by TriumphST** [comment]
std::malloc

**Comment by TriumphST** [comment]
Ako ste na tom? Vedeli by ste mi poslat nejaky zaznam z kamery na testovanie? A spravil som prehravanie tak ze ulozene png-cka by mali byt vo formate aaaa_0.png, aaaa_1.png, aaaa_2.png ... Poisledne cislo skratka urcuje poradie.

**Comment by TriumphST** [comment]
Chalani spravite to, alebo mi donesiete kameru a dokoncim to ja?

**Comment by pavelpetrovic** [comment]
ak ziskate pointer na obrazove data (napr. cez CBitmap alebo CImage), tak ich jednoducho skopirujte cez CopyMemory() do svojej struktury... dajte vediet, ak s tym neviete pohnut.

**Comment by muller29** [comment]
Ja mám kameru, zoberem ti, tak to bude rychlejsie ked vies hned otestovat.
