### ISSUE TITLE
Camera ROI

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#35]
Skusit kamera RIO a zistit ci sa to zvacsilo FPS ...

**Comment by TriumphST** [comment]
![image](https://user-images.githubusercontent.com/33921752/49698014-8f387500-fbbe-11e8-9f7a-fd699f48c792.png)

**Comment by TriumphST** [comment]
![image](https://user-images.githubusercontent.com/33921752/49698043-dfafd280-fbbe-11e8-9470-c3720bd15cb3.png)

**Comment by TriumphST** [comment]
![komponent_diagram_v4](https://user-images.githubusercontent.com/33921752/49800087-f41ed700-fd46-11e8-904f-28d5d06d1a1d.png)

**Comment by pavelpetrovic** [comment]
a co prepojenie grabber -> storage?
naopak loader -> storage neviem ci naozaj treba?
ale loader -> gui asi ano...

he?

**Comment by TriumphST** [comment]
@muller29 vedel by si pls napisat mail ze vieme menit ROI ale napriek tomu ja fps stale rovnake, ci nevedia aky prepinac to prenastavi?

**Comment by TriumphST** [comment]
Roi sa nastavuje ale FPS sa nemení, uzatvaram a problém s fps presúvam do nového issue #42
