### ISSUE TITLE
implementacia: gui - nastavenia - subory

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2018-FMFI/vysokorychlostna-kamera#36]
https://msdn.microsoft.com/en-us/library/Bb776913(v=VS.85).aspx

**Comment by muller29** [comment]
https://docs.microsoft.com/en-us/windows/desktop/learnwin32/example--the-open-dialog-box?fbclid=IwAR2N2zDiSRU3yKSybHFINZ4OqEkM0dndjjHLkH1fmOFB9XNpbVNRjnu803Q

**Comment by TriumphST** [comment]
Nastavenie súboru z ktorého sa prehráva uložený zaznam je spravené cez button.
