### ISSUE TITLE
Spravit wiki zapisnice

### ISSUE THREAD

**Issue by TriumphST** [TIS2018-FMFI/vysokorychlostna-kamera#8]

**Comment by Emilmilill** [comment]
hotovo. 
Mali by sme sa ale rozhodnúť, kde si primárne organizovať prácu, aby sme všetko nemali aj na Drive, aj na Wiki, aj v Issues :D

**Comment by pavelpetrovic** [comment]
na wiki prosim piste zapisnicu zo stretnutia hned na stretnuti. vsetko, co robite na projekte by malo mat issue, v jeho vlakne o tom diskutujete. na drive mozete vytvarat drafty dokumentov...
